version: '3.8'

services:
  # Backend API
  mcp-backend:
    image: node:18-alpine
    ports:
      - "3001:3001"
    working_dir: /app
    command: >
      sh -c "
        echo '🚀 Iniciando MCP Backend...' &&
        apk add --no-cache git python3 make g++ &&
        git clone https://github.com/peuscategui/mcpefclocal.git /tmp/repo &&
        cp -r /tmp/repo/mcp-server/mcp-client-backend/* /app/ &&
        rm -rf /tmp/repo &&
        npm ci --only=production &&
        node server.js
      "
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ENCRYPT=true
      - DB_TRUST_SERVER_CERTIFICATE=true
      - MCP_HOST=mcp-sql-server
      - MCP_PORT=3000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NODE_ENV=production
      - PORT=3001
      - LOG_LEVEL=info
    
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    networks:
      - mcp-network

  # Frontend Web
  mcp-frontend:
    image: node:18-alpine
    ports:
      - "3003:3003"
    working_dir: /app
    command: >
      sh -c "
        echo '🚀 Iniciando MCP Frontend...' &&
        apk add --no-cache git python3 make g++ &&
        git clone https://github.com/peuscategui/mcpefclocal.git /tmp/repo &&
        cp -r /tmp/repo/mcp-server/mcp-client-web/* /app/ &&
        rm -rf /tmp/repo &&
        npm ci &&
        npm run build &&
        npm run start
      "
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://192.168.40.197:3001
      - PORT=3003
      - HOSTNAME=0.0.0.0
      
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3003/', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    networks:
      - mcp-network
    
    depends_on:
      - mcp-backend

  # MCP SQL Server
  mcp-sql-server:
    image: node:18-alpine
    command: >
      sh -c "
        echo '🚀 Iniciando MCP SQL Server...' &&
        apk add --no-cache git python3 make g++ &&
        git clone https://github.com/peuscategui/mcpefclocal.git /tmp/repo &&
        cp -r /tmp/repo/mcp-server/* /app/ &&
        rm -rf /tmp/repo &&
        npm ci --only=production &&
        node src/server.js
      "
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - MCP_HOST=0.0.0.0
      - MCP_PORT=3000
      - LOG_LEVEL=info
      - DB_ENCRYPT=true
      - DB_TRUST_SERVER_CERTIFICATE=true
    
    networks:
      - mcp-network
    
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  mcp-network:
    external: true
    name: mcp-efc-comercial_mcp-network

